# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/validation.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/validation.ipynb 2
import collections
import math
import os
import re
from pathlib import Path

import numpy as np
import pandas as pd

import plotly.graph_objects as go
import plotly.figure_factory as ff
from omnisync.visualization.pitch import Pitch,plot_pitch

from fastcore.foundation import L
