# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_pitch_control.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_pitch_control.ipynb 4
import os
import re

import numpy as np
import pandas as pd
from fastcore.foundation import L
